version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: licencegenapi-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: LicenceDB
    networks:
      - licence-network
    volumes:
      - db-data:/var/lib/postgresql/data

  licencegenapi:
    build:
      context: .
    container_name: licencegenapi-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - licence-network

networks:
  licence-network:
    driver: bridge

volumes:
  db-data: